In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns 
import matplotlib
from sklearn.impute import KNNImputer
from sklearn.tree import DecisionTreeClassifier
import warnings
warnings.filterwarnings('ignore')
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.metrics import precision_score,recall_score,f1_score,cohen_kappa_score
import statsmodels.api as sm
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import PowerTransformer
from sklearn.model_selection import cross_val_score
import pylab as pl
pd.options.display.max_rows=None
pd.options.display.max_columns=None
from xgboost import XGBClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_excel('/content/drive/My Drive/Capstone/transformed_df.xlsx')

In [ ]:
df.head(2)

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term,Year,Month
0,343481,NaN,NaN,71.310442,16000,16000.0,36 months,2.794780,18.386629,D,D2,Manager,10+ years,RENT,76.282376,Source Verified,2018-04-01,0,n,NaN,NaN,debt_consolidation,Debt consolidation,482xx,MI,12.97,1,Sep-2006,1,20.0,NaN,3.493362,0,21.086054,4.0,5.252012,w,77.234847,12782.62,15.828322,5222.14,12.196131,28.918987,0.0,0.0,0.0,Feb-2019,4.563472,Mar-2019,Feb-2019,1,20.0,1,Joint App,155000.0,25.71,Source Verified,0,0,43.413863,3,1,2,3,2.0,65.932533,100.0,1,5,22.451932,51.0,37.714065,2,4,2,3.085858,7084.0,10763.0,7.2,0,0,137.0,14.460281,1.077967,1.068123,2,2.0,NaN,2.0,NaN,1,1.567930,2.060831,1.513386,2.028252,2.539273,2.900628,3.205608,2.088951,3.487390,0.0,0,1,1.427368,96.0,0.0,0,0,35.191359,54.301766,60.262431,90.793486,38618.0,Mar-2007,1.0,1.0,20.0,52.2,5.0,16.0,0.0,0.0,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,2018,4
1,343482,NaN,NaN,87.134314,28675,28675.0,60 months,3.107894,21.092636,E,E5,officer,10+ years,MORTGAGE,74.441265,Verified,2018-04-01,0,n,NaN,NaN,debt_consolidation,Debt consolidation,114xx,NY,17.00,0,Jul-2005,1,NaN,NaN,4.147580,0,54.144615,69.4,7.973929,w,100.229002,26107.93,17.444102,8674.05,11.711664,41.597367,0.0,0.0,0.0,Feb-2019,4.757724,Mar-2019,Feb-2019,0,NaN,1,Individual,NaN,NaN,NaN,0,0,61.236392,1,15,0,0,36.0,112.009436,116.0,2,4,82.265507,105.0,40.381219,0,1,1,1.969564,23197.0,6014.0,79.5,0,0,153.0,13.939855,1.077967,1.068123,2,2.0,NaN,0.0,NaN,0,1.857586,2.447468,1.782384,2.954972,5.117636,2.296616,3.286357,2.486553,4.139374,0.0,0,0,1.124303,100.0,75.0,0,0,45.366029,91.225286,82.316757,156.824990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN,2018,4

In [ ]:
df.isnull().sum()

Unnamed: 0                                         0
id                                            150792
member_id                                     150792
loan_amnt                                          0
funded_amnt                                        0
funded_amnt_inv                                    0
term                                               0
int_rate                                           0
installment                                        0
grade                                              0
sub_grade                                          0
emp_title                                      13107
emp_length                                     12866
home_ownership                                     0
annual_inc                                         0
verification_status                                0
issue_d                                            0
loan_status                                        0
pymnt_plan                                         0
url                                           150792
desc                                          150792
purpose                                            0
title                                              0
zip_code                                           0
addr_state                                         0
dti                                              363
delinq_2yrs                                        0
earliest_cr_line                                   0
inq_last_6mths                                     0
mths_since_last_delinq                         84604
mths_since_last_record                        129970
open_acc                                           0
pub_rec                                            0
revol_bal                                          0
revol_util                                       204
total_acc                                          0
initial_list_status                                0
out_prncp                                          0
out_prncp_inv                                      0
total_pymnt                                        0
total_pymnt_inv                                    0
total_rec_prncp                                    0
total_rec_int                                      0
total_rec_late_fee                                 0
recoveries                                         0
collection_recovery_fee                            0
last_pymnt_d                                     216
last_pymnt_amnt                                    0
next_pymnt_d                                   26001
last_credit_pull_d                                 1
collections_12_mths_ex_med                         0
mths_since_last_major_derog                   115980
policy_code                                        0
application_type                                   0
annual_inc_joint                              128353
dti_joint                                     128353
verification_status_joint                     128803
acc_now_delinq                                     0
tot_coll_amt                                       0
tot_cur_bal                                        0
open_acc_6m                                        0
open_act_il                                        0
open_il_12m                                        0
open_il_24m                                        0
mths_since_rcnt_il                              5886
total_bal_il                                       0
il_util                                        25056
open_rv_12m                                        0
open_rv_24m                                        0
max_bal_bc                                         0
all_util                                          40
total_rev_hi_lim                                   0
inq_fi                                             0
total_cu_tl                                        0
inq_last_12m                                       0
acc_open_past_24mths                               0
avg_cur_bal                                       11
bc_open_to_buy                                  2087
bc_util                                         2152
chargeoff_within_12_mths                           0
delinq_amnt                                        0
mo_sin_old_il_acct                              5886
mo_sin_old_rev_tl_op                               0
mo_sin_rcnt_rev_tl_op                              0
mo_sin_rcnt_tl                                     0
mort_acc                                           0
mths_since_recent_bc                            1961
mths_since_recent_bc_dlq                      120966
mths_since_recent_inq                          18731
mths_since_recent_revol_delinq                107531
num_accts_ever_120_pd                              0
num_actv_bc_tl                                     0
num_actv_rev_tl                                    0
num_bc_sats                                        0
num_bc_tl                                          0
num_il_tl                                          0
num_op_rev_tl                                      0
num_rev_accts                                      0
num_rev_tl_bal_gt_0                                0
num_sats                                           0
num_tl_120dpd_2m                                4568
num_tl_30dpd                                       0
num_tl_90g_dpd_24m                                 0
num_tl_op_past_12m                                 0
pct_tl_nvr_dlq                                     1
percent_bc_gt_75                                2092
pub_rec_bankruptcies                               0
tax_liens                                          0
tot_hi_cred_lim                                    0
total_bal_ex_mort                                  0
total_bc_limit                                     0
total_il_high_credit_limit                         0
revol_bal_joint                               128353
sec_app_earliest_cr_line                      128353
sec_app_inq_last_6mths                        128353
sec_app_mort_acc                              128353
sec_app_open_acc                              128353
sec_app_revol_util                            128777
sec_app_open_act_il                           128353
sec_app_num_rev_accts                         128353
sec_app_chargeoff_within_12_mths              128353
sec_app_collections_12_mths_ex_med            128353
sec_app_mths_since_last_major_derog           143202
hardship_flag                                      0
hardship_type                                 150559
hardship_reason                               150559
hardship_status                               150559
deferral_term                                 150559
hardship_amount                               150559
hardship_start_date                           150559
hardship_end_date                             150559
payment_plan_start_date                       150559
hardship_length                               150559
hardship_dpd                                  150559
hardship_loan_status                          150559
orig_projected_additional_accrued_interest    150594
hardship_payoff_balance_amount                150559
hardship_last_payment_amount                  150559
disbursement_method                                0
debt_settlement_flag                               0
debt_settlement_flag_date                     150495
settlement_status                             150495
settlement_date                               150495
settlement_amount                             150495
settlement_percentage                         150495
settlement_term                               150495
Year                                               0
Month                                              0
dtype: int64

In [ ]:
df.shape

(150792, 148)

In [ ]:
df=df[['Unnamed: 0',
'loan_amnt',
'term',
'int_rate',
'installment',
'sub_grade',
'home_ownership',
'annual_inc',
'verification_status',
'purpose',
'delinq_2yrs',
'open_acc',
'pub_rec',
'revol_bal',
'total_acc',
'initial_list_status',
'out_prncp',
'total_pymnt',
'total_rec_prncp',
'total_rec_int',
'total_rec_late_fee',
'last_pymnt_amnt',
'application_type',
'tot_coll_amt',
'tot_cur_bal',
'open_acc_6m',
'open_act_il',
'open_il_12m',
'open_il_24m',
'total_bal_il',
'open_rv_12m',
'open_rv_24m',
'max_bal_bc',
'total_rev_hi_lim',
'inq_fi',
'total_cu_tl',
'inq_last_12m',
'acc_open_past_24mths',
'mo_sin_old_rev_tl_op',
'mo_sin_rcnt_rev_tl_op',
'mo_sin_rcnt_tl',
'mort_acc',
'num_accts_ever_120_pd',
'num_actv_bc_tl',
'num_actv_rev_tl',
'num_bc_sats',
'num_bc_tl',
'num_il_tl',
'num_op_rev_tl',
'num_rev_accts',
'num_rev_tl_bal_gt_0',
'num_sats',
'num_tl_op_past_12m',
'pub_rec_bankruptcies',
'tot_hi_cred_lim',
'total_bal_ex_mort',
'total_bc_limit',
'total_il_high_credit_limit',
'disbursement_method',
'loan_status',
'il_util',
'mths_since_recent_inq',
'mths_since_rcnt_il',
'mo_sin_old_il_acct',
'bc_util',
'percent_bc_gt_75',
'bc_open_to_buy',
'mths_since_recent_bc',
'dti',
'revol_util',
'all_util',
'avg_cur_bal',
'pct_tl_nvr_dlq']]

In [ ]:
df= df.rename({'Unnamed: 0':'ID'}, axis=1)

In [ ]:
df = df.set_index('ID')

In [ ]:
df.head(2)

,loan_amnt,term,int_rate,installment,sub_grade,home_ownership,annual_inc,verification_status,purpose,delinq_2yrs,open_acc,pub_rec,revol_bal,total_acc,initial_list_status,out_prncp,total_pymnt,total_rec_prncp,total_rec_int,total_rec_late_fee,last_pymnt_amnt,application_type,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,total_bal_il,open_rv_12m,open_rv_24m,max_bal_bc,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_op_past_12m,pub_rec_bankruptcies,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,disbursement_method,loan_status,il_util,mths_since_recent_inq,mths_since_rcnt_il,mo_sin_old_il_acct,bc_util,percent_bc_gt_75,bc_open_to_buy,mths_since_recent_bc,dti,revol_util,all_util,avg_cur_bal,pct_tl_nvr_dlq
ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
343481,71.310442,36 months,2.794780,18.386629,D2,RENT,76.282376,Source Verified,debt_consolidation,1,3.493362,0,21.086054,5.252012,w,77.234847,15.828322,12.196131,28.918987,0.0,4.563472,Joint App,0,43.413863,3,1,2,3,65.932533,1,5,22.451932,37.714065,2,4,2,3.085858,14.460281,1.077967,1.068123,2,1,1.567930,2.060831,1.513386,2.028252,2.539273,2.900628,3.205608,2.088951,3.487390,1.427368,0,35.191359,54.301766,60.262431,90.793486,Cash,0,100.0,2.0,2.0,137.0,7.2,0.0,10763.0,2.0,12.97,4.0,51.0,7084.0,96.0
343482,87.134314,60 months,3.107894,21.092636,E5,MORTGAGE,74.441265,Verified,debt_consolidation,0,4.147580,0,54.144615,7.973929,w,100.229002,17.444102,11.711664,41.597367,0.0,4.757724,Individual,0,61.236392,1,15,0,0,112.009436,2,4,82.265507,40.381219,0,1,1,1.969564,13.939855,1.077967,1.068123,2,0,1.857586,2.447468,1.782384,2.954972,5.117636,2.296616,3.286357,2.486553,4.139374,1.124303,0,45.366029,91.225286,82.316757,156.824990,Cash,0,116.0,0.0,36.0,153.0,79.5,75.0,6014.0,2.0,17.00,69.4,105.0,23197.0,100.0

In [ ]:
df.shape

(150792, 72)

In [ ]:
df.isnull().sum()

loan_amnt                         0
term                              0
int_rate                          0
installment                       0
sub_grade                         0
home_ownership                    0
annual_inc                        0
verification_status               0
purpose                           0
delinq_2yrs                       0
open_acc                          0
pub_rec                           0
revol_bal                         0
total_acc                         0
initial_list_status               0
out_prncp                         0
total_pymnt                       0
total_rec_prncp                   0
total_rec_int                     0
total_rec_late_fee                0
last_pymnt_amnt                   0
application_type                  0
tot_coll_amt                      0
tot_cur_bal                       0
open_acc_6m                       0
open_act_il                       0
open_il_12m                       0
open_il_24m                       0
total_bal_il                      0
open_rv_12m                       0
open_rv_24m                       0
max_bal_bc                        0
total_rev_hi_lim                  0
inq_fi                            0
total_cu_tl                       0
inq_last_12m                      0
acc_open_past_24mths              0
mo_sin_old_rev_tl_op              0
mo_sin_rcnt_rev_tl_op             0
mo_sin_rcnt_tl                    0
mort_acc                          0
num_accts_ever_120_pd             0
num_actv_bc_tl                    0
num_actv_rev_tl                   0
num_bc_sats                       0
num_bc_tl                         0
num_il_tl                         0
num_op_rev_tl                     0
num_rev_accts                     0
num_rev_tl_bal_gt_0               0
num_sats                          0
num_tl_op_past_12m                0
pub_rec_bankruptcies              0
tot_hi_cred_lim                   0
total_bal_ex_mort                 0
total_bc_limit                    0
total_il_high_credit_limit        0
disbursement_method               0
loan_status                       0
il_util                       25056
mths_since_recent_inq         18731
mths_since_rcnt_il             5886
mo_sin_old_il_acct             5886
bc_util                        2152
percent_bc_gt_75               2092
bc_open_to_buy                 2087
mths_since_recent_bc           1961
dti                             363
revol_util                      204
all_util                         40
avg_cur_bal                      11
pct_tl_nvr_dlq                    1
dtype: int64

In [ ]:
df_num = df.select_dtypes(include=np.number)

In [ ]:
df_num.shape

(150792, 64)

In [ ]:
df_num.head(2)

,loan_amnt,int_rate,installment,annual_inc,delinq_2yrs,open_acc,pub_rec,revol_bal,total_acc,out_prncp,total_pymnt,total_rec_prncp,total_rec_int,total_rec_late_fee,last_pymnt_amnt,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,total_bal_il,open_rv_12m,open_rv_24m,max_bal_bc,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_op_past_12m,pub_rec_bankruptcies,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,loan_status,il_util,mths_since_recent_inq,mths_since_rcnt_il,mo_sin_old_il_acct,bc_util,percent_bc_gt_75,bc_open_to_buy,mths_since_recent_bc,dti,revol_util,all_util,avg_cur_bal,pct_tl_nvr_dlq
ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
343481,71.310442,2.794780,18.386629,76.282376,1,3.493362,0,21.086054,5.252012,77.234847,15.828322,12.196131,28.918987,0.0,4.563472,0,43.413863,3,1,2,3,65.932533,1,5,22.451932,37.714065,2,4,2,3.085858,14.460281,1.077967,1.068123,2,1,1.567930,2.060831,1.513386,2.028252,2.539273,2.900628,3.205608,2.088951,3.487390,1.427368,0,35.191359,54.301766,60.262431,90.793486,0,100.0,2.0,2.0,137.0,7.2,0.0,10763.0,2.0,12.97,4.0,51.0,7084.0,96.0
343482,87.134314,3.107894,21.092636,74.441265,0,4.147580,0,54.144615,7.973929,100.229002,17.444102,11.711664,41.597367,0.0,4.757724,0,61.236392,1,15,0,0,112.009436,2,4,82.265507,40.381219,0,1,1,1.969564,13.939855,1.077967,1.068123,2,0,1.857586,2.447468,1.782384,2.954972,5.117636,2.296616,3.286357,2.486553,4.139374,1.124303,0,45.366029,91.225286,82.316757,156.824990,0,116.0,0.0,36.0,153.0,79.5,75.0,6014.0,2.0,17.00,69.4,105.0,23197.0,100.0

In [ ]:
df_cat = df.select_dtypes(exclude=np.number)

In [ ]:
df_cat.shape

(150792, 8)

In [ ]:
df_cat.head(2)

,term,sub_grade,home_ownership,verification_status,purpose,initial_list_status,application_type,disbursement_method
ID,,,,,,,,
343481,36 months,D2,RENT,Source Verified,debt_consolidation,w,Joint App,Cash
343482,60 months,E5,MORTGAGE,Verified,debt_consolidation,w,Individual,Cash

In [ ]:
df_cat.isnull().sum()

term                   0
sub_grade              0
home_ownership         0
verification_status    0
purpose                0
initial_list_status    0
application_type       0
disbursement_method    0
dtype: int64

**Using Data: trasnsformed_df; KNNImputation method;**

In [ ]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors= 5)
imputed = imputer.fit_transform(df_num)
df_imputed = pd.DataFrame(imputed, columns=df_num.columns)

In [ ]:
df_imputed.shape

(150792, 64)

In [ ]:
df_imputed.head(2)

,loan_amnt,int_rate,installment,annual_inc,delinq_2yrs,open_acc,pub_rec,revol_bal,total_acc,out_prncp,total_pymnt,total_rec_prncp,total_rec_int,total_rec_late_fee,last_pymnt_amnt,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,total_bal_il,open_rv_12m,open_rv_24m,max_bal_bc,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_op_past_12m,pub_rec_bankruptcies,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,loan_status,il_util,mths_since_recent_inq,mths_since_rcnt_il,mo_sin_old_il_acct,bc_util,percent_bc_gt_75,bc_open_to_buy,mths_since_recent_bc,dti,revol_util,all_util,avg_cur_bal,pct_tl_nvr_dlq
0,71.310442,2.794780,18.386629,76.282376,1.0,3.493362,0.0,21.086054,5.252012,77.234847,15.828322,12.196131,28.918987,0.0,4.563472,0.0,43.413863,3.0,1.0,2.0,3.0,65.932533,1.0,5.0,22.451932,37.714065,2.0,4.0,2.0,3.085858,14.460281,1.077967,1.068123,2.0,1.0,1.567930,2.060831,1.513386,2.028252,2.539273,2.900628,3.205608,2.088951,3.487390,1.427368,0.0,35.191359,54.301766,60.262431,90.793486,0.0,100.0,2.0,2.0,137.0,7.2,0.0,10763.0,2.0,12.97,4.0,51.0,7084.0,96.0
1,87.134314,3.107894,21.092636,74.441265,0.0,4.147580,0.0,54.144615,7.973929,100.229002,17.444102,11.711664,41.597367,0.0,4.757724,0.0,61.236392,1.0,15.0,0.0,0.0,112.009436,2.0,4.0,82.265507,40.381219,0.0,1.0,1.0,1.969564,13.939855,1.077967,1.068123,2.0,0.0,1.857586,2.447468,1.782384,2.954972,5.117636,2.296616,3.286357,2.486553,4.139374,1.124303,0.0,45.366029,91.225286,82.316757,156.824990,0.0,116.0,0.0,36.0,153.0,79.5,75.0,6014.0,2.0,17.00,69.4,105.0,23197.0,100.0

In [ ]:
df_imputed.index = df_num.index

In [ ]:
df_imputed.head(2)

,loan_amnt,int_rate,installment,annual_inc,delinq_2yrs,open_acc,pub_rec,revol_bal,total_acc,out_prncp,total_pymnt,total_rec_prncp,total_rec_int,total_rec_late_fee,last_pymnt_amnt,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,total_bal_il,open_rv_12m,open_rv_24m,max_bal_bc,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_op_past_12m,pub_rec_bankruptcies,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,loan_status,il_util,mths_since_recent_inq,mths_since_rcnt_il,mo_sin_old_il_acct,bc_util,percent_bc_gt_75,bc_open_to_buy,mths_since_recent_bc,dti,revol_util,all_util,avg_cur_bal,pct_tl_nvr_dlq
ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
343481,71.310442,2.794780,18.386629,76.282376,1.0,3.493362,0.0,21.086054,5.252012,77.234847,15.828322,12.196131,28.918987,0.0,4.563472,0.0,43.413863,3.0,1.0,2.0,3.0,65.932533,1.0,5.0,22.451932,37.714065,2.0,4.0,2.0,3.085858,14.460281,1.077967,1.068123,2.0,1.0,1.567930,2.060831,1.513386,2.028252,2.539273,2.900628,3.205608,2.088951,3.487390,1.427368,0.0,35.191359,54.301766,60.262431,90.793486,0.0,100.0,2.0,2.0,137.0,7.2,0.0,10763.0,2.0,12.97,4.0,51.0,7084.0,96.0
343482,87.134314,3.107894,21.092636,74.441265,0.0,4.147580,0.0,54.144615,7.973929,100.229002,17.444102,11.711664,41.597367,0.0,4.757724,0.0,61.236392,1.0,15.0,0.0,0.0,112.009436,2.0,4.0,82.265507,40.381219,0.0,1.0,1.0,1.969564,13.939855,1.077967,1.068123,2.0,0.0,1.857586,2.447468,1.782384,2.954972,5.117636,2.296616,3.286357,2.486553,4.139374,1.124303,0.0,45.366029,91.225286,82.316757,156.824990,0.0,116.0,0.0,36.0,153.0,79.5,75.0,6014.0,2.0,17.00,69.4,105.0,23197.0,100.0

In [ ]:
df_imputed['term'] = df['term']
df_imputed['sub_grade'] = df['sub_grade']
df_imputed['home_ownership'] = df['home_ownership']
df_imputed['verification_status'] = df['verification_status']
df_imputed['purpose'] = df['purpose']
df_imputed['initial_list_status'] = df['initial_list_status']
df_imputed['application_type'] = df['application_type']
df_imputed['disbursement_method'] = df['disbursement_method']

In [ ]:
df_imputed.head(2)

,loan_amnt,int_rate,installment,annual_inc,delinq_2yrs,open_acc,pub_rec,revol_bal,total_acc,out_prncp,total_pymnt,total_rec_prncp,total_rec_int,total_rec_late_fee,last_pymnt_amnt,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,total_bal_il,open_rv_12m,open_rv_24m,max_bal_bc,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_op_past_12m,pub_rec_bankruptcies,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,loan_status,il_util,mths_since_recent_inq,mths_since_rcnt_il,mo_sin_old_il_acct,bc_util,percent_bc_gt_75,bc_open_to_buy,mths_since_recent_bc,dti,revol_util,all_util,avg_cur_bal,pct_tl_nvr_dlq,term,sub_grade,home_ownership,verification_status,purpose,initial_list_status,application_type,disbursement_method
ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
343481,71.310442,2.794780,18.386629,76.282376,1.0,3.493362,0.0,21.086054,5.252012,77.234847,15.828322,12.196131,28.918987,0.0,4.563472,0.0,43.413863,3.0,1.0,2.0,3.0,65.932533,1.0,5.0,22.451932,37.714065,2.0,4.0,2.0,3.085858,14.460281,1.077967,1.068123,2.0,1.0,1.567930,2.060831,1.513386,2.028252,2.539273,2.900628,3.205608,2.088951,3.487390,1.427368,0.0,35.191359,54.301766,60.262431,90.793486,0.0,100.0,2.0,2.0,137.0,7.2,0.0,10763.0,2.0,12.97,4.0,51.0,7084.0,96.0,36 months,D2,RENT,Source Verified,debt_consolidation,w,Joint App,Cash
343482,87.134314,3.107894,21.092636,74.441265,0.0,4.147580,0.0,54.144615,7.973929,100.229002,17.444102,11.711664,41.597367,0.0,4.757724,0.0,61.236392,1.0,15.0,0.0,0.0,112.009436,2.0,4.0,82.265507,40.381219,0.0,1.0,1.0,1.969564,13.939855,1.077967,1.068123,2.0,0.0,1.857586,2.447468,1.782384,2.954972,5.117636,2.296616,3.286357,2.486553,4.139374,1.124303,0.0,45.366029,91.225286,82.316757,156.824990,0.0,116.0,0.0,36.0,153.0,79.5,75.0,6014.0,2.0,17.00,69.4,105.0,23197.0,100.0,60 months,E5,MORTGAGE,Verified,debt_consolidation,w,Individual,Cash

In [ ]:
df_imputed.shape

(150792, 72)

In [ ]:
df_imputed.isnull().sum()

loan_amnt                     0
int_rate                      0
installment                   0
annual_inc                    0
delinq_2yrs                   0
open_acc                      0
pub_rec                       0
revol_bal                     0
total_acc                     0
out_prncp                     0
total_pymnt                   0
total_rec_prncp               0
total_rec_int                 0
total_rec_late_fee            0
last_pymnt_amnt               0
tot_coll_amt                  0
tot_cur_bal                   0
open_acc_6m                   0
open_act_il                   0
open_il_12m                   0
open_il_24m                   0
total_bal_il                  0
open_rv_12m                   0
open_rv_24m                   0
max_bal_bc                    0
total_rev_hi_lim              0
inq_fi                        0
total_cu_tl                   0
inq_last_12m                  0
acc_open_past_24mths          0
mo_sin_old_rev_tl_op          0
mo_sin_rcnt_rev_tl_op         0
mo_sin_rcnt_tl                0
mort_acc                      0
num_accts_ever_120_pd         0
num_actv_bc_tl                0
num_actv_rev_tl               0
num_bc_sats                   0
num_bc_tl                     0
num_il_tl                     0
num_op_rev_tl                 0
num_rev_accts                 0
num_rev_tl_bal_gt_0           0
num_sats                      0
num_tl_op_past_12m            0
pub_rec_bankruptcies          0
tot_hi_cred_lim               0
total_bal_ex_mort             0
total_bc_limit                0
total_il_high_credit_limit    0
loan_status                   0
il_util                       0
mths_since_recent_inq         0
mths_since_rcnt_il            0
mo_sin_old_il_acct            0
bc_util                       0
percent_bc_gt_75              0
bc_open_to_buy                0
mths_since_recent_bc          0
dti                           0
revol_util                    0
all_util                      0
avg_cur_bal                   0
pct_tl_nvr_dlq                0
term                          0
sub_grade                     0
home_ownership                0
verification_status           0
purpose                       0
initial_list_status           0
application_type              0
disbursement_method           0
dtype: int64

In [ ]:
df_imputed.to_csv('/content/drive/My Drive/Capstone/knn_imputed_data.csv')

In [ ]:
df_imputed = pd.read_excel('/content/drive/My Drive/Capstone/knn_imputed_data.csv')

XLRDError: ignored

In [ ]:
df_imputed = pd.get_dummies(df_imputed, drop_first =True)

In [ ]:
X=df_imputed.drop('loan_status',axis=1)

In [ ]:
y = df_imputed[['loan_status']]

**Using statsmodels approach**

In [ ]:
Xc=sm.add_constant(X)
model = sm.Logit(y,X).fit()
model.summary()

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.082909
         Iterations: 35

/usr/local/lib/python3.7/dist-packages/statsmodels/base/model.py:512: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:            loan_status   No. Observations:               150792
Model:                          Logit   Df Residuals:                   150674
Method:                           MLE   Df Model:                          117
Date:                Sun, 15 Aug 2021   Pseudo R-squ.:                  0.6419
Time:                        19:04:18   Log-Likelihood:                -12502.
converged:                      False   LL-Null:                       -34916.
Covariance Type:            nonrobust   LLR p-value:                     0.000
=======================================================================================================
                                          coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------
loan_amnt                              -0.0535      0.021     -2.608      0.009      -0.094      -0.013
int_rate                               -6.7494      0.670    -10.074      0.000      -8.062      -5.436
installment                             2.8950      0.095     30.524      0.000       2.709       3.081
annual_inc                             -0.0043      0.002     -2.081      0.037      -0.008      -0.000
delinq_2yrs                             0.0149      0.025      0.596      0.551      -0.034       0.064
open_acc                               -0.3992      0.728     -0.548      0.584      -1.827       1.028
pub_rec                                 0.0800      0.037      2.157      0.031       0.007       0.153
revol_bal                              -0.0156      0.006     -2.706      0.007      -0.027      -0.004
total_acc                               0.1619      0.084      1.926      0.054      -0.003       0.327
out_prncp                              -0.1000      0.005    -20.197      0.000      -0.110      -0.090
total_pymnt                            -3.1106      0.117    -26.541      0.000      -3.340      -2.881
total_rec_prncp                        -1.2120      0.123     -9.815      0.000      -1.454      -0.970
total_rec_int                          -0.1670      0.014    -11.727      0.000      -0.195      -0.139
total_rec_late_fee                      0.0437      0.001     31.811      0.000       0.041       0.046
last_pymnt_amnt                         1.7320      0.178      9.753      0.000       1.384       2.080
tot_coll_amt                         5.024e-07   1.52e-06      0.330      0.741   -2.48e-06    3.48e-06
tot_cur_bal                             0.0016      0.010      0.163      0.871      -0.017       0.020
open_acc_6m                             0.0679      0.025      2.743      0.006       0.019       0.116
open_act_il                            -0.0147      0.017     -0.871      0.384      -0.048       0.018
open_il_12m                             0.0106      0.044      0.242      0.808      -0.075       0.097
open_il_24m                            -0.0326      0.029     -1.125      0.261      -0.089       0.024
total_bal_il                            0.0097      0.005      1.816      0.069      -0.001       0.020
open_rv_12m                            -0.0435      0.034     -1.278      0.201      -0.110       0.023
open_rv_24m                            -0.0304      0.022     -1.396      0.163      -0.073       0.012
max_bal_bc                              0.0016      0.002      0.705      0.481      -0.003       0.006
total_rev_hi_lim                        0.0403      0.011      3.666      0.000       0.019       0.062
inq_fi                                  0.0031      0.015      0.212      0.832      -0.025       0.031
total_cu_tl                            -0.0025      0.008     -0.317      0.751      -0.018       0.013
inq_last_12m                            0.0103      0.010      1.011      0.312      -0.010       0.030
acc_open_past_24mths                    0.2047      0.081      2.537      0.011       0.047       0.363
mo_sin_old_rev_tl_op                 2.584e-05      0.006      0.005      0.996      -0.011       0.011
mo_sin_rcnt_rev_tl_op                  -0.1095      0.043     -2.533      0.011      -0.194      -0.025
mo_sin_rcnt_tl                          0.0433      0.056      0.780      0.436      -0.066       0.152
mort_acc                               -0.0098      0.017     -0.568      0.570      -0.044       0.024
num_accts_ever_120_pd                  -0.0351      0.018     -2.000      0.045      -0.070      -0.001
num_actv_bc_tl                          0.0447      0.092      0.485      0.628      -0.136       0.225
num_actv_rev_tl                         0.5088      0.199      2.562      0.010       0.120       0.898
num_bc_sats                             0.1924      0.105      1.832      0.067      -0.013       0.398
num_bc_tl                               0.0387      0.078      0.495      0.621      -0.115       0.192
num_il_tl                              -0.0941      0.064     -1.460      0.144      -0.220       0.032
num_op_rev_tl                          -0.3730      0.170     -2.189      0.029      -0.707      -0.039
num_rev_accts                           0.0229      0.123      0.186      0.852      -0.218       0.264
num_rev_tl_bal_gt_0                    -0.4946      0.198     -2.496      0.013      -0.883      -0.106
num_sats                                0.3036      0.722      0.420      0.674      -1.112       1.719
num_tl_op_past_12m                     -0.0506      0.100     -0.506      0.613      -0.246       0.145
pub_rec_bankruptcies                   -0.0378      0.066     -0.576      0.565      -0.167       0.091
tot_hi_cred_lim                        -0.0051      0.017     -0.296      0.767      -0.039       0.029
total_bal_ex_mort                      -0.0044      0.004     -1.052      0.293      -0.013       0.004
total_bc_limit                         -0.0111      0.003     -3.179      0.001      -0.018      -0.004
total_il_high_credit_limit             -0.0063      0.003     -1.990      0.047      -0.013   -9.59e-05
il_util                                 0.0010      0.002      0.662      0.508      -0.002       0.004
mths_since_recent_inq                  -0.0124      0.004     -3.182      0.001      -0.020      -0.005
mths_since_rcnt_il                      0.0006      0.001      0.696      0.486      -0.001       0.002
mo_sin_old_il_acct                     -0.0003      0.000     -0.828      0.407      -0.001       0.000
bc_util                                -0.0031      0.002     -1.536      0.125      -0.007       0.001
percent_bc_gt_75                        0.0010      0.001      1.030      0.303      -0.001       0.003
bc_open_to_buy                       4.084e-07   2.16e-06      0.189      0.850   -3.82e-06    4.64e-06
mths_since_recent_bc                    0.0005      0.001      0.732      0.464      -0.001       0.002
dti                                     0.0003      0.001      0.408      0.683      -0.001       0.002
revol_util                              0.0033      0.002      1.448      0.148      -0.001       0.008
all_util                               -0.0019      0.002     -1.000      0.317      -0.006       0.002
avg_cur_bal                         -1.656e-06   2.32e-06     -0.712      0.476   -6.21e-06     2.9e-06
pct_tl_nvr_dlq                          0.0009      0.003      0.338      0.735      -0.004       0.006
term_ 60 months                         2.1884      0.227      9.633      0.000       1.743       2.634
sub_grade_A2                            1.0475      0.260      4.036      0.000       0.539       1.556
sub_grade_A3                            2.0628      0.263      7.848      0.000       1.548       2.578
sub_grade_A4                            2.6886      0.284      9.460      0.000       2.132       3.246
sub_grade_A5                            3.3462      0.312     10.735      0.000       2.735       3.957
sub_grade_B1                            4.4143      0.376     11.747      0.000       3.678       5.151
sub_grade_B2                            4.9461      0.397     12.453      0.000       4.168       5.725
sub_grade_B3                            5.2931      0.421     12.570      0.000       4.468       6.118
sub_grade_B4                            5.4315      0.441     12.316      0.000       4.567       6.296
sub_grade_B5                            6.2866      0.486     12.937      0.000       5.334       7.239
sub_grade_C1                            6.4985      0.511     12.726      0.000       5.498       7.499
sub_grade_C2                            6.9573      0.548     12.689      0.000       5.883       8.032
sub_grade_C3                            7.0872      0.566     12.511      0.000       5.977       8.197
sub_grade_C4                            7.4780      0.600     12.464      0.000       6.302       8.654
sub_grade_C5                            7.7339      0.632     12.229      0.000       6.494       8.973
sub_grade_D1                            8.1905      0.678     12.073      0.000       6.861       9.520
sub_grade_D2                            8.5870      0.704     12.196      0.000       7.207       9.967
sub_grade_D3                            8.8239      0.733     12.038      0.000       7.387      10.260
sub_grade_D4                            8.8848      0.758     11.718      0.000       7.399      10.371
sub_grade_D5                            9.2808      0.797     11.651      0.000       7.720      10.842
sub_grade_E1                            9.2515      0.846     10.935      0.000       7.593      10.910
sub_grade_E2                           10.2344      0.856     11.950      0.000       8.556      11.913
sub_grade_E3                            9.4515      0.878     10.769      0.000       7.731      11.172
sub_grade_E4                            9.3212      0.896     10.403      0.000       7.565      11.077
sub_grade_E5                            9.5669      0.911     10.507      0.000       7.782      11.351
sub_grade_F1                            9.6180      0.971      9.907      0.000       7.715      11.521
sub_grade_F2                            9.3037      1.086      8.564      0.000       7.174      11.433
sub_grade_F3                           10.4200      1.061      9.817      0.000       8.340      12.500
sub_grade_F4                           10.0444      1.093      9.188      0.000       7.902      12.187
sub_grade_F5                            9.5489      1.133      8.428      0.000       7.328      11.770
sub_grade_G1                            9.4274      1.092      8.631      0.000       7.287      11.568
sub_grade_G2                           11.5095      1.514      7.602      0.000       8.542      14.477
sub_grade_G3                           11.3256      1.704      6.647      0.000       7.986      14.665
sub_grade_G4                           11.7447      1.655      7.098      0.000       8.501      14.988
sub_grade_G5                           -0.5391    528.379     -0.001      0.999   -1036.143    1035.065
home_ownership_MORTGAGE                28.8076      1.421     20.277      0.000      26.023      31.592
home_ownership_OWN                     28.8361      1.420     20.303      0.000      26.052      31.620
home_ownership_RENT                    28.9263      1.419     20.392      0.000      26.146      31.707
verification_status_Source Verified     0.0630      0.045      1.396      0.163      -0.025       0.152
verification_status_Verified            0.1089      0.050      2.183      0.029       0.011       0.207
purpose_credit_card                    -0.0745      0.168     -0.444      0.657      -0.403       0.255
purpose_debt_consolidation             -0.0273      0.164     -0.166      0.868      -0.349       0.295
purpose_home_improvement               -0.0955      0.177     -0.541      0.589      -0.442       0.251
purpose_house                          -0.3074      0.223     -1.376      0.169      -0.745       0.130
purpose_major_purchase                 -0.1183      0.193     -0.612      0.541      -0.497       0.261
purpose_medical                         0.0309      0.209      0.148      0.882      -0.379       0.441
purpose_moving                          0.1049      0.246      0.426      0.670      -0.377       0.587
purpose_other                          -0.1123      0.171     -0.656      0.512      -0.448       0.223
purpose_renewable_energy               -0.9743      0.982     -0.992      0.321      -2.900       0.951
purpose_small_business                  0.3842      0.209      1.837      0.066      -0.026       0.794
purpose_vacation                       -0.4720      0.274     -1.724      0.085      -1.008       0.064
purpose_wedding                        -3.7146     59.618     -0.062      0.950    -120.564     113.134
initial_list_status_w                  -0.3047      0.050     -6.091      0.000      -0.403      -0.207
application_type_Joint App              0.0734      0.053      1.376      0.169      -0.031       0.178
disbursement_method_DirectPay          -0.0754      0.088     -0.862      0.389      -0.247       0.096
=======================================================================================================

Possibly complete quasi-separation: A fraction 0.12 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

**Model 3.1 - Logistic Regression**

In [ ]:
lr = LogisticRegression()
sc = StandardScaler()
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size= .30,random_state=10)
scaledXtrain = sc.fit_transform(Xtrain)
scaledXtest = sc.transform(Xtest)
lr.fit(scaledXtrain,ytrain)
print("Training Accuracy")
print(lr.score(Xtrain,ytrain))
print("Testing Accuracy")
print(lr.score(scaledXtest,ytest))
scoreslr = cross_val_score(lr, scaledXtrain,ytrain, cv=10, scoring='roc_auc')
print("Cross Validation Accuracy")
print(np.mean(scoreslr))
predictedlr = lr.predict(scaledXtest)
print(confusion_matrix(ytest,predictedlr))
print(classification_report(ytest,predictedlr))

Training Accuracy
0.8187183811129848
Testing Accuracy
0.9781599540209558
Cross Validation Accuracy
0.9463348595566579
[[42418    62]
 [  926  1832]]
              precision    recall  f1-score   support

         0.0       0.98      1.00      0.99     42480
         1.0       0.97      0.66      0.79      2758

    accuracy                           0.98     45238
   macro avg       0.97      0.83      0.89     45238
weighted avg       0.98      0.98      0.98     45238

**Model 3.2 - Decision Tree Classifier**

In [ ]:
dt = DecisionTreeClassifier()
sc = StandardScaler()
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size= .30,random_state=10)
scaledXtrain = sc.fit_transform(Xtrain)
scaledXtest = sc.transform(Xtest)
dt.fit(scaledXtrain,ytrain)
print("Training Accuracy")
print(dt.score(Xtrain,ytrain))
print("Testing Accuracy")
print(dt.score(scaledXtest,ytest))
scoresdt = cross_val_score(dt, scaledXtrain,ytrain, cv=10, scoring='roc_auc')
print("Cross Validation Accuracy")
print(np.mean(scoresdt))
predicted_dt = dt.predict(scaledXtest)
print(confusion_matrix(ytest,predicted_dt))
print(classification_report(ytest,predicted_dt))

Training Accuracy
0.8854425223108551
Testing Accuracy
0.9619788673239312
Cross Validation Accuracy
0.8484051041028918
[[41513   967]
 [  753  2005]]
              precision    recall  f1-score   support

         0.0       0.98      0.98      0.98     42480
         1.0       0.67      0.73      0.70      2758

    accuracy                           0.96     45238
   macro avg       0.83      0.85      0.84     45238
weighted avg       0.96      0.96      0.96     45238

**Model 3.3 - RandomForestClassifier**

In [ ]:
rf = RandomForestClassifier()
sc = StandardScaler()
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size= .30,random_state=10)
scaledXtrain = sc.fit_transform(Xtrain)
scaledXtest = sc.transform(Xtest)
rf.fit(scaledXtrain,ytrain)
print("Training Accuracy")
print(rf.score(Xtrain,ytrain))
print("Testing Accuracy")
print(rf.score(scaledXtest,ytest))
scoresrf = cross_val_score(rf, scaledXtrain,ytrain, cv=10, scoring='roc_auc')
print("Cross Validation Accuracy")
print(np.mean(scoresrf))
predicted_rf = rf.predict(scaledXtest)
print(confusion_matrix(ytest,predicted_rf))
print(classification_report(ytest,predicted_rf))

Training Accuracy
0.9345453511946492
Testing Accuracy
0.9717052035899023
Cross Validation Accuracy
0.9298261458488272
[[42476     4]
 [ 1276  1482]]
              precision    recall  f1-score   support

         0.0       0.97      1.00      0.99     42480
         1.0       1.00      0.54      0.70      2758

    accuracy                           0.97     45238
   macro avg       0.98      0.77      0.84     45238
weighted avg       0.97      0.97      0.97     45238

**Model 3.5- KNN CLassifier**

In [ ]:
knn = KNeighborsClassifier()
sc = StandardScaler()
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size= .30,random_state=10)
scaledXtrain = sc.fit_transform(Xtrain)
scaledXtest = sc.transform(Xtest)
knn.fit(scaledXtrain,ytrain)
print("Training Accuracy")
print(knn.score(Xtrain,ytrain))
print("Testing Accuracy")
print(knn.score(scaledXtest,ytest))
scoresknn = cross_val_score(knn, scaledXtrain,ytrain, cv=10, scoring='roc_auc')
print("Cross Validation Accuracy")
print(np.mean(scoresknn))
predicted_knn = knn.predict(scaledXtest)
print(confusion_matrix(ytest,predicted_knn))
print(classification_report(ytest,predicted_knn))

Training Accuracy
0.9380222445383406
Testing Accuracy
0.9405809275387949

**Model 3.7 - AdaBoostClassifer**

In [ ]:
ad = AdaBoostClassifier()
sc = StandardScaler()
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size= .30,random_state=10)
scaledXtrain = sc.fit_transform(Xtrain)
scaledXtest = sc.transform(Xtest)
ad.fit(scaledXtrain,ytrain)
print("Training Accuracy")
print(ad.score(Xtrain,ytrain))
print("Testing Accuracy")
print(ad.score(scaledXtest,ytest))
scoresad = cross_val_score(ad, scaledXtrain,ytrain, cv=10, scoring='roc_auc')
print("Cross Validation Accuracy")
print(np.mean(scoresad))
predicted_ad = ad.predict(scaledXtest)
print(confusion_matrix(ytest,predicted_ad))
print(classification_report(ytest,predicted_ad))

Training Accuracy
0.9380222445383406
Testing Accuracy
0.9721915204032009
Cross Validation Accuracy
0.9336402670483336
[[42391    89]
 [ 1169  1589]]
              precision    recall  f1-score   support

         0.0       0.97      1.00      0.99     42480
         1.0       0.95      0.58      0.72      2758

    accuracy                           0.97     45238
   macro avg       0.96      0.79      0.85     45238
weighted avg       0.97      0.97      0.97     45238

**Model 3.8 - XGBoostClassifier**

In [ ]:
xgb = XGBClassifier()
sc = StandardScaler()
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size= .30,random_state=10)
scaledXtrain = sc.fit_transform(Xtrain)
scaledXtest = sc.transform(Xtest)
xgb.fit(scaledXtrain,ytrain)
print("Training Accuracy")
print(xgb.score(Xtrain,ytrain))
print("Testing Accuracy")
print(xgb.score(scaledXtest,ytest))
scoresxgb = cross_val_score(xgb, scaledXtrain,ytrain, cv=10, scoring='roc_auc')
print("Cross Validation Accuracy")
print(np.mean(scoresxgb))
predicted_xgb = xgb.predict(scaledXtest)
print(confusion_matrix(ytest,predicted_xgb))
print(classification_report(ytest,predicted_xgb))